version: 2

project_name: ghpp

builds:
  - id: ghpp
    main: .
    binary: ghpp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"

release:
  github:
    owner: douhashi
    name: ghpp
